-- ============================================================
-- Pokemon Wiz — Full Database Schema for Supabase
-- Generated by Drizzle ORM
-- Paste the entire file into Supabase SQL Editor and run it
-- ============================================================

CREATE TABLE "agent_card_limits" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer,
	"card_name" text NOT NULL,
	"set_name" text,
	"purchased_count" integer DEFAULT 0,
	"max_allowed" integer DEFAULT 2,
	"reached_limit" boolean DEFAULT false
);

CREATE TABLE "agent_credentials" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer,
	"outlet" text NOT NULL,
	"login_email" text,
	"login_password_encrypted" text,
	"api_key_encrypted" text,
	"profile_url" text,
	"created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "agent_proxies" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer,
	"proxy_type" text,
	"proxy_url" text NOT NULL,
	"provider" text,
	"is_active" boolean DEFAULT true,
	"last_tested" timestamp with time zone,
	"test_passed" boolean,
	"assigned_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "agent_proxies_agent_id_unique" UNIQUE("agent_id")
);

CREATE TABLE "agent_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer,
	"outlet" text NOT NULL,
	"session_data" text,
	"logged_in" boolean DEFAULT false,
	"last_refreshed" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "agents" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"outlet" text,
	"outlet_account_label" text,
	"fund_balance" numeric(12, 2) DEFAULT '0',
	"status" text DEFAULT 'idle',
	"cards_bought" integer DEFAULT 0,
	"total_spent" numeric(12, 2) DEFAULT '0',
	"last_active" timestamp with time zone,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "audit_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer,
	"campaign_id" integer,
	"event_type" text NOT NULL,
	"level" text DEFAULT 'info',
	"message" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "campaign_agents" (
	"id" serial PRIMARY KEY NOT NULL,
	"campaign_id" integer,
	"agent_id" integer,
	"is_lead" boolean DEFAULT false,
	"assigned_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "campaigns" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"card_name" text NOT NULL,
	"set_name" text,
	"card_number" text,
	"max_price" numeric(10, 2),
	"target_quantity" integer DEFAULT 10,
	"priority" text DEFAULT 'normal',
	"status" text DEFAULT 'active',
	"fulfilled" integer DEFAULT 0,
	"total_spent" numeric(12, 2) DEFAULT '0',
	"sources" text DEFAULT 'tcgplayer,pokemoncenter,ebay',
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "condition_disputes" (
	"id" serial PRIMARY KEY NOT NULL,
	"inventory_id" integer,
	"listed_condition" text NOT NULL,
	"received_condition" text NOT NULL,
	"status" text DEFAULT 'open',
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"resolved_at" timestamp with time zone
);

CREATE TABLE "deposits" (
	"id" serial PRIMARY KEY NOT NULL,
	"method" text,
	"amount" numeric(12, 2) NOT NULL,
	"currency" text DEFAULT 'USD',
	"status" text DEFAULT 'pending',
	"provider_payment_id" text,
	"wallet_address" text,
	"tx_hash" text,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "inventory" (
	"id" serial PRIMARY KEY NOT NULL,
	"card_name" text NOT NULL,
	"set_name" text NOT NULL,
	"card_number" text,
	"rarity" text,
	"condition" text,
	"purchase_price" numeric(10, 2) NOT NULL,
	"market_price" numeric(10, 2),
	"sale_price" numeric(10, 2),
	"image_url" text,
	"tcgplayer_id" text,
	"acquired_by" integer,
	"campaign_id" integer,
	"source_outlet" text,
	"status" text DEFAULT 'inventory',
	"acquired_at" timestamp with time zone DEFAULT now(),
	"sold_at" timestamp with time zone
);

CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"shop_listing_id" integer,
	"customer_name" text NOT NULL,
	"customer_email" text NOT NULL,
	"shipping_address" jsonb NOT NULL,
	"total" numeric(10, 2) NOT NULL,
	"payment_method" text,
	"payment_id" text,
	"status" text DEFAULT 'pending',
	"tracking_number" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "outlet_listings" (
	"id" serial PRIMARY KEY NOT NULL,
	"card_name" text NOT NULL,
	"set_name" text,
	"outlet" text NOT NULL,
	"outlet_listing_url" text,
	"price" numeric(10, 2),
	"seller" text,
	"condition" text,
	"in_stock" boolean DEFAULT true,
	"listing_id" text,
	"first_seen" timestamp with time zone DEFAULT now(),
	"last_seen" timestamp with time zone DEFAULT now()
);

CREATE TABLE "profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"display_name" text,
	"main_balance" numeric(12, 2) DEFAULT '0',
	"crypto_balance" numeric(16, 8) DEFAULT '0',
	"created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "shipping_labels" (
	"id" serial PRIMARY KEY NOT NULL,
	"shop_listing_id" integer,
	"order_id" integer,
	"carrier" text,
	"service" text,
	"tracking_number" text,
	"label_url" text,
	"cost" numeric(6, 2),
	"created_at" timestamp with time zone DEFAULT now(),
	"shipped_at" timestamp with time zone,
	"delivered_at" timestamp with time zone
);

CREATE TABLE "shop_listings" (
	"id" serial PRIMARY KEY NOT NULL,
	"inventory_id" integer,
	"title" text NOT NULL,
	"description" text,
	"price" numeric(10, 2) NOT NULL,
	"condition" text,
	"images" jsonb,
	"status" text DEFAULT 'active',
	"stripe_product_id" text,
	"stripe_price_id" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"sold_at" timestamp with time zone
);

CREATE TABLE "transactions" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" text,
	"amount" numeric(12, 2) NOT NULL,
	"currency" text DEFAULT 'USD',
	"source" text,
	"from_entity" text,
	"to_entity" text,
	"reference_id" text,
	"campaign_id" integer,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now()
);

-- Foreign Keys
ALTER TABLE "agent_card_limits" ADD CONSTRAINT "agent_card_limits_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade;
ALTER TABLE "agent_credentials" ADD CONSTRAINT "agent_credentials_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade;
ALTER TABLE "agent_proxies" ADD CONSTRAINT "agent_proxies_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE set null;
ALTER TABLE "agent_sessions" ADD CONSTRAINT "agent_sessions_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id");
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id");
ALTER TABLE "campaign_agents" ADD CONSTRAINT "campaign_agents_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE cascade;
ALTER TABLE "campaign_agents" ADD CONSTRAINT "campaign_agents_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade;
ALTER TABLE "condition_disputes" ADD CONSTRAINT "condition_disputes_inventory_id_inventory_id_fk" FOREIGN KEY ("inventory_id") REFERENCES "public"."inventory"("id") ON DELETE cascade;
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_acquired_by_agents_id_fk" FOREIGN KEY ("acquired_by") REFERENCES "public"."agents"("id");
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id");
ALTER TABLE "orders" ADD CONSTRAINT "orders_shop_listing_id_shop_listings_id_fk" FOREIGN KEY ("shop_listing_id") REFERENCES "public"."shop_listings"("id");
ALTER TABLE "shipping_labels" ADD CONSTRAINT "shipping_labels_shop_listing_id_shop_listings_id_fk" FOREIGN KEY ("shop_listing_id") REFERENCES "public"."shop_listings"("id") ON DELETE cascade;
ALTER TABLE "shipping_labels" ADD CONSTRAINT "shipping_labels_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id");
ALTER TABLE "shop_listings" ADD CONSTRAINT "shop_listings_inventory_id_inventory_id_fk" FOREIGN KEY ("inventory_id") REFERENCES "public"."inventory"("id") ON DELETE cascade;
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id");

-- Indexes
CREATE UNIQUE INDEX "idx_unique_agent_card" ON "agent_card_limits" USING btree ("agent_id","card_name","set_name");
CREATE UNIQUE INDEX "idx_unique_agent_outlet" ON "agent_sessions" USING btree ("agent_id","outlet");
CREATE INDEX "idx_audit_agent" ON "audit_logs" USING btree ("agent_id","created_at");
CREATE INDEX "idx_audit_campaign" ON "audit_logs" USING btree ("campaign_id","created_at");
CREATE UNIQUE INDEX "idx_unique_campaign_agent" ON "campaign_agents" USING btree ("campaign_id","agent_id");
